### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-addons#15]
Images should be resized if they are crazy big when added. 800px x 600px seems like a reasonable default for now.

**Comment by xmatthewx** [comment]
This isn't mvp. We will scale images #16 with max-width for now so the thing doesn't break. When we resize, we should retain some resolution for when they move from the small sidebar to full-fledged Webmaker.

**Comment by toolness** [comment]
Is it ok to just set the scale % to whatever fits within 800x600 when they first add the image to the canvas? That way it defaults to something reasonable, but they can continue to scale it to full-size if they really want (perhaps e.g. if they want to show only a particular part of the image close-up or something, I dunno).

Full disclosure: partly I am just suggesting this because it'd be really, really easy to implement this way. :P

**Comment by xmatthewx** [comment]
I trust your judgement. Mainly, I was suggesting we focus on #16 to make things visually fit, rather than adding an engine to actually resize the bits and bytes. We might be saying the same thing. 

On a related note: I like your simple slider for scaling the text size. Might be nice to add that for images as well.

**Comment by toolness** [comment]
Ok, I think I fixed this one, though I'm honestly not sure if it's #16... I'm not clear on what the difference is, but you can try adding e.g. http://placehold.it/1024x768 to see what it looks like.
