### ISSUE TITLE
Smoothly add first image

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-addons#45]
I like the animation in #10. It's fun and helps explain this unfamiliar experience. When the sidebar is already open, it works smoothly. 

Adding the first image, however, there's a big lag between step 2 and 3. 
1. animate image on page
2. open sidebar
3. animate image in sidebar

The sidebar background colors aren't there initially. If the image lag is unavoidable, adding the colors and a spinner will help.

**Comment by davidascher** [comment]
If this weren't just a proof of concept, I'd argue that we need to think
pretty deeply about the sidebar -- how to introduce the feature, how to
have the slurping of an image when sidebar is closed hint that the sidebar
is there, etc.  But given that it's just a proof of concept, I don't think
it's worth spending a lot of time on this.

**Comment by xmatthewx** [comment]
Fair enough. Keeping open in case there's a quick fix. Otherwise, @toolness feel free to close.

**Comment by xmatthewx** [comment]
To make a good first impression, but keep things simple:
- give iframe background gray
- add a big spinner
- adjust order of operations

**Comment by toolness** [comment]
By "adjust order of operations" I assume you mean the thing about parallelizing the firebase sync with the loading of UI code, rather than doing one after the other?

**Comment by toolness** [comment]
Hmm, so upon further reflection it seems the order of operations thing will actually take a lot longer to implement than I anticipated, and it might not even be particularly useful, so I'm going to bail on it. (More useful would probably be to optimize the requirejs bundle so that the page loads faster, but that's a bit of a hassle too... still, if the page load time is a significant concern, we can do it.)
